/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compras.vista;

import seguridad.vista.*;
import compras.vista.*;
import compras.modelo.daoCuentasPorPagar;
import compras.controlador.clsCuentasPorPagar;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmProcesoCuentasPorPagar extends javax.swing.JInternalFrame {

  

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Concepto");
        modelo.addColumn("ID Compras");
        modelo.addColumn("ID Proveedor");
        modelo.addColumn("Cuenta de documento");
        modelo.addColumn("Saldo de cuenta");
        modelo.addColumn("Valor de cuenta");
        modelo.addColumn("Referencia de cuenta");
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        List<clsCuentasPorPagar> concepto = cuentasDAO.select();
        tablaVendedores.setModel(modelo);
        String[] dato = new String[5];
        for (int i = 0; i < concepto.size(); i++) {
            dato[0] = Integer.toString(concepto.get(i).getConid());
            dato[1] = concepto.get(i).getConnombre();
            dato[2] = concepto.get(i).getConefecto();
            dato[3] = concepto.get(i).getConestatus().toString();
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarConcepto() {
        clsCuentasPorPagar conceptoAConsultar = new clsCuentasPorPagar();
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        conceptoAConsultar.setConid(Integer.parseInt(txtbuscado.getText()));
        conceptoAConsultar = cuentasDAO.query(conceptoAConsultar);
        txtConNombre.setText(conceptoAConsultar.getConnombre());
        txtConEfecto.setText(conceptoAConsultar.getConefecto());
        ComboEstado.setSelectedItem(conceptoAConsultar.getConestatus());
        
    }

    public frmProcesoCuentasPorPagar() {
        initComponents();
        llenadoDeTablas();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        label5 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        txtConNombre = new javax.swing.JTextField();
        txtConEfecto = new javax.swing.JTextField();
        ComboEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtConEfecto1 = new javax.swing.JTextField();
        txtConEfecto2 = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        txtConEfecto3 = new javax.swing.JTextField();
        label9 = new javax.swing.JLabel();
        txtConEfecto4 = new javax.swing.JTextField();
        label10 = new javax.swing.JLabel();
        txtConEfecto5 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proceso Cuentas por pagar");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 95, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 95, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("?");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 40, -1));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label1.setText("Cuentas por pagar");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 100, -1));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Codigo producto a buscar:");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        txtbuscado.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 102, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 95, -1));

        tablaVendedores.setBackground(new java.awt.Color(204, 255, 255));
        tablaVendedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 50, 860, 430));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label5.setText("Referencia de la cuenta");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 20, 13, -1));

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 100, -1));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label6.setText("ID de compras");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label7.setText("ID de proveedor");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtConNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtConNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtConNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 220, -1));

        txtConEfecto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConEfecto.setForeground(new java.awt.Color(255, 255, 255));
        txtConEfecto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtConEfecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConEfectoActionPerformed(evt);
            }
        });
        getContentPane().add(txtConEfecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 160, -1));

        ComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(ComboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("ID de Concepto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtConEfecto1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConEfecto1.setForeground(new java.awt.Color(255, 255, 255));
        txtConEfecto1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtConEfecto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, -1));

        txtConEfecto2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConEfecto2.setForeground(new java.awt.Color(255, 255, 255));
        txtConEfecto2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtConEfecto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConEfecto2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtConEfecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 220, -1));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label8.setText("Cuenta de documento");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtConEfecto3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConEfecto3.setForeground(new java.awt.Color(255, 255, 255));
        txtConEfecto3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtConEfecto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConEfecto3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtConEfecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, -1));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label9.setText("Saldo de cuenta");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtConEfecto4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConEfecto4.setForeground(new java.awt.Color(255, 255, 255));
        txtConEfecto4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtConEfecto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConEfecto4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtConEfecto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, -1));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label10.setText("Valor de la cuenta");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txtConEfecto5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConEfecto5.setForeground(new java.awt.Color(255, 255, 255));
        txtConEfecto5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtConEfecto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConEfecto5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtConEfecto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, -1));

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar conceptoAEliminar = new clsCuentasPorPagar();
        conceptoAEliminar.setConid(Integer.parseInt(txtbuscado.getText()));
        cuentasDAO.delete(conceptoAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar conceptoAInsertar = new clsCuentasPorPagar();
        conceptoAInsertar.setConnombre(txtConNombre.getText());
        conceptoAInsertar.setConefecto(txtConEfecto.getText());
        if (ComboEstado.getSelectedItem().equals("Activo")) {
            conceptoAInsertar.setConestatus(Boolean.parseBoolean("0"));
        } else {
            conceptoAInsertar.setConestatus(Boolean.parseBoolean("1"));
        }
        cuentasDAO.insert(conceptoAInsertar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "INGRESE EL CODIGO DEL PROVEEDOR QUE DESEA BUSCAR,ELIMINAR O REGISTRAR");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
//        // TODO add your handling code here:
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar conceptoAActualizar = new clsCuentasPorPagar();
        conceptoAActualizar.setConid(Integer.parseInt(txtbuscado.getText()));
        conceptoAActualizar.setConnombre(txtConNombre.getText());
        conceptoAActualizar.setConefecto(txtConEfecto.getText());
        if (ComboEstado.getSelectedItem().equals("Activo")) {
            conceptoAActualizar.setConestatus(true);
        } else {
            conceptoAActualizar.setConestatus(false);
        }
        cuentasDAO.update(conceptoAActualizar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       
        ComboEstado.setSelectedItem("");
        txtbuscado.setText("");
        txtConNombre.setText("");
        txtConEfecto.setText("");
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtConEfectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConEfectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConEfectoActionPerformed

    private void txtConEfecto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConEfecto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConEfecto2ActionPerformed

    private void txtConEfecto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConEfecto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConEfecto3ActionPerformed

    private void txtConEfecto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConEfecto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConEfecto4ActionPerformed

    private void txtConEfecto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConEfecto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConEfecto5ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEstado;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtConEfecto;
    private javax.swing.JTextField txtConEfecto1;
    private javax.swing.JTextField txtConEfecto2;
    private javax.swing.JTextField txtConEfecto3;
    private javax.swing.JTextField txtConEfecto4;
    private javax.swing.JTextField txtConEfecto5;
    private javax.swing.JTextField txtConNombre;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
